### ISSUE TITLE
Webpack 4 support

### ISSUE THREAD

**Issue by jantimon** [morganbarrett/html-webpack-cheeky-insert-plugin#1]
Hey :)

thanks for that cool extension!  
A feature like this was often requested by react/vue developers.  

Right now you are not using the newest version of the [webpack plugin api](https://github.com/webpack/tapable) which will deprecation warnings for everyone who is using the plugin.

The meta-tag example works a little bit around the built in `meta` option of the html webpack plugin. Is there anything missing in the current meta implementation?

**Comment by morganbarrett** [comment]
Fixed issue
